# spring:
#   jpa:
#     database: POSTGRESQL

spring:
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://172.19.0.20:5432/postgres
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false

# spring:
#   datasource:
#     url: ${DATABASE_URL}
#     username: ${DATABASE_USERNAME}
#     password: ${DATABASE_PASSWORD}

server:
  port: 8081

# debug: true